### ISSUE TITLE
Anonymous feedback

### ISSUE THREAD

**Issue by BGMwebdev** [BGMwebdev/love-running-project#2]
In order to **provide anonymous feedback**, as a **user**, I can **hide my identity in the poll response**

## ACCEPTANCE CRITERIA:
- Acceptance criteria 1: The option should be provided as a checkbox
- Acceptance criteria 2: The checkbox should be checked by default
- Acceptance criteria 3:The option should appear next to the submit button

## TASKS:
- [ ] Task 1: Update the view; The poll design (HTML and CSS), to include the checkbox and show the name of the submitter
- [ ] Task 2: Create a new field in the model the track the username
- [ ] Task 3: Update the controller function
- [ ] Task 4: Update unit test scripts
- [ ] Task 5: Test the functionality

**Comment by BGMwebdev** [comment]
This is completed
